site_name: Grapesea's Notebook
repo_url: https://github.com/Grapesea/Notebook
repo_name: Notebook
theme: 
  name: material
  font:
    text: "Times New Roman"
    code: "Roboto Mono"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  language: zh
  logo: graph/logo.png
# pages:
# - [index.md, Home]
# - [about.md, About]
  favicon: graph/logo.png
  features:
    - search.highlight
#    - navigation.instant
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - attr_list

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页: index.md
  - ZJU课程笔记: 
    - 导航栏: zju/index.md
    - 资源整合: zju/mix_resource.md
    - 大一教训总结: zju/exp1.md
    - 大一笔记拾遗: 
      - 导航: zju/12/index.md
      - 数据结构基础: 
        - 概述: zju/12/fds/index.md
        - Heap: zju/12/fds/heap.md
        - Graph: zju/12/fds/graph.md
    - 大二秋冬笔记: 
      - 导航: zju/21/index.md
      - 高级数据结构与算法分析: 
        - 概述: zju/21/ads/index.md
        - 高级数据结构:
          - AVL Tree & Splay Tree & Red-Black Tree & B+ Tree(√): zju/21/ads/tree.md
          - Amortized Analysis(√): zju/21/ads/amortized.md
          - Inverted File Index(√): zju/21/ads/fileindex.md
          - Leftist Heap & Skew Heap & Binomial Queue(√): zju/21/ads/heap.md
        - 算法分析:
          - Backtracking(√): zju/21/ads/bt.md
          - Divide and Conquer(√): zju/21/ads/dc.md
          - Dynamic Programming(√): zju/21/ads/dp.md
          - Greedy Algorithm(√): zju/21/ads/greedy.md
          - P&NP Completeness(√): zju/21/ads/np.md
          - Approximation Algorithm(√): zju/21/ads/approx.md
          - Local Search(√): zju/21/ads/local.md
          - Randomized Algorithm(√): zju/21/ads/random.md
          - Parallel Algorithm(√) : zju/21/ads/parallel.md
          - External Sort(√): zju/21/ads/exsort.md
        - Project:
          - Project 1-Comparing Different Search Trees: zju/21/ads/proj/1.md
          - Project 2-Shortest Path Algorithm with Heaps: zju/21/ads/proj/2.md
          - Project 3-Recover the Design: zju/21/ads/proj/3.md
          - Project 5-Three Partition: zju/21/ads/proj/5.md
      - 计算机组成: 
        - 概述: zju/21/co/index.md
        - 笔记:
          - 导航: zju/21/co/note/index.md
          - Chap1笔记: zju/21/co/note/co1.md
          - Chap2笔记: zju/21/co/note/co2.md
          - Chap3笔记: zju/21/co/note/co3.md
          - Chap4笔记: zju/21/co/note/co4.md
          - Chap5笔记: zju/21/co/note/co5.md
          - Chap6笔记: zju/21/co/note/co6.md
        - lab总结:
          - 导航: zju/21/co/lab/index.md
          - lab0:Vivado_Starter: zju/21/co/lab/lab0.md
          - lab1:Warmup: zju/21/co/lab/lab1.md
          - lab2:SCPU: zju/21/co/lab/lab2.md
          - lab3:Multiplier/Divider/Floating-Point Adder: zju/21/co/lab/lab3.md
          - lab4:CPU(Single Cycle): zju/21/co/lab/lab4.md
          - lab5:PipelineCPU: zju/21/co/lab/lab5.md
      - 面向对象程序设计: 
        - 概述: zju/21/oop/index.md
        - 笔记: 
          - Week1: zju/21/oop/1.md
          - Week2: zju/21/oop/2.md
          - Week3: zju/21/oop/3.md
          - Week4: zju/21/oop/4.md
          - Week5: zju/21/oop/5.md
          - Week6: zju/21/oop/6.md
          - 考前抱佛脚: zju/21/oop/review.md
        - 课程作业题干: 
          - Lab 1: zju/21/oop/lab/1.md
          - Lab 2: zju/21/oop/lab/2.md
          - Lab 3: zju/21/oop/lab/3.md
          - Lab 4: zju/21/oop/lab/4.md
          - Lab 5: zju/21/oop/lab/5.md
          - Lab 6: zju/21/oop/lab/6.md
          - Project 7: zju/21/oop/lab/7.md
      - 概率论与数理统计: 
        - 概述: zju/21/prob/index.md
        - 概率论: zju/21/prob/prob.md
        - 数理统计: zju/21/prob/statistic.md
      - 普通物理学II(H): 
        - 概述: zju/21/phy/index.md
      - 普通物理学实验II:
        - 概述: zju/21/phylab/index.md
      - 马克思主义基本原理(H):
        - 概述: zju/21/marx/index.md
      - 生命教育概论:
        - 概述: zju/21/life/index.md
        - 笔记: zju/21/life/life.md
      - 经济法理论与实务:
        - 概述: zju/21/eco/index.md
      - 万物运转的奥秘（已退课）:
        - 概述: zju/21/physec/index.md
    - 大二春夏笔记: 
      - 导航: zju/22/index.md
      - 数据库系统: 
        - 概述: zju/22/db/index.md
        - 笔记: zju/22/db/db.md
      - 计算机体系结构:
        - 概述: zju/22/arch/index.md
      - 离散数学: 
        - 概述: zju/22/dm/index.md
        - 笔记: zju/22/dm/dm.md
      - 工程图学(H):
        - 概述: zju/22/graphics/index.md
      - 生命科学导论(H):
        - 概述: zju/22/bio/index.md
        - 笔记: zju/22/bio/bio.md
      - 中国书画鉴赏:
        - 概述: zju/22/art/index.md
  - csdiy课程笔记: 
    - csdiy课程笔记导航: csdiy/index.md
    - CS61C:
      - 课程计划: csdiy/cs61c/index.md
    - CS70: 
      - 课程计划: csdiy/cs70/index.md
      - Proof & Stable matching: csdiy/cs70/1.md
      - Graph & Number theory & RSA: csdiy/cs70/2.md
      - Counting & Probability: csdiy/cs70/3.md
    - CS188: 
      - 课程计划: csdiy/cs188/index.md
      - intro & search: csdiy/cs188/1.md
      - A* search & Heuristics: csdiy/cs188/2.md
      - CSPs: csdiy/cs188/3.md
      - Game Trees: csdiy/cs188/4.md
      - MDPs: csdiy/cs188/5.md
      - Appendix:Logic: csdiy/cs188/appendix.md
    - NJU-SICP:
      - 课程计划: csdiy/sicp-NJU/index.md
      - lec1-6: csdiy/sicp-NJU/lec1-6.md
    - NJU-ICSPA:
      - 课程计划: csdiy/icspa-NJU/index.md
    - CS106L:
      - 课程计划: csdiy/cs106l/index.md
      - Lec1-Brief Introduction: csdiy/cs106l/1intro.md
      - Lec2-Types and Struct: csdiy/cs106l/2types.md
      - Lec3&4-Streams, Initialization and References: csdiy/cs106l/3_4streams_init_ref.md
      - Lec5&6-Containers,Iterators and Pointers: csdiy/cs106l/5_6container_iterator.md
      - Lec7&8-Classes, Template Classes: csdiy/cs106l/7_8classes_templates.md
      - Lec9-Template Functions: csdiy/cs106l/9templatefuncs.md
      - Lec10-Functions and Lambdas: csdiy/cs106l/10functions.md
      - Lec11-Operators: csdiy/cs106l/11operators.md
      - Lec12-Special Member Functions: csdiy/cs106l/12specialmembers.md
      - Lec13-Move Semantics: csdiy/cs106l/13movesemantics.md
      - Lec14-std::optional and Type Safety: csdiy/cs106l/14optional.md
      - Lec15-RAII, Smart Pointers, and Building C++ Projects: csdiy/cs106l/15raii.md
    - MIT 6.1600:
      - 课程计划: csdiy/mit6.1600/index.md
    - CSAPP:
      - 课程计划: csdiy/csapp/index.md
    - 李沐动手学深度学习:
      - 课程计划: csdiy/d2l/index.md
      - Note 1:深度学习简介与工具准备: csdiy/d2l/intro.md
      - Note 2:数学基础: csdiy/d2l/mathbasics.md
    - Datawhale Mathematical Modeling:
      - 课程计划: csdiy/datawhale_mm/index.md
      - Chap 1:解析方法与几何模型: csdiy/datawhale_mm/1.md  
      - Chap 2:微分方程与动力系统: csdiy/datawhale_mm/2.md
      - Chap 3:函数极值与规划模型: csdiy/datawhale_mm/3.md
      - Chap 4:复杂网络与图论模型: csdiy/datawhale_mm/4.md
      - Chap 5:进化计算与群体智能: csdiy/datawhale_mm/5.md
      - Chap 6:数据处理与拟合模型: csdiy/datawhale_mm/6.md
      - Chap 7:权重生成与评价模型: csdiy/datawhale_mm/7.md
      - Chap 8:时间序列与投资模型: csdiy/datawhale_mm/8.md
      - Chap 9:机器学习与统计模型: csdiy/datawhale_mm/9.md
      - Chap 10:图像、文本与信号数据: csdiy/datawhale_mm/10.md
    - Datawhale Mathematics for Artificial Intelligence:
      - 课程计划: csdiy/datawhale_m4ai/index.md
      - Chap 2-6:线性代数/解析几何/矩阵分解/向量微积分/概率与统计: csdiy/datawhale_m4ai/2-6.md
      - Chap 7:连续优化: csdiy/datawhale_m4ai/7.md
      - Chap 8:当模型遇上数据: csdiy/datawhale_m4ai/8.md
      - Chap 9:线性回归: csdiy/datawhale_m4ai/9.md
      - Chap 10:降维与主成分分析: csdiy/datawhale_m4ai/10.md
      - Chap 11:密度估计和Gauss混合模型: csdiy/datawhale_m4ai/11.md
      - Chap 12:分类和支持向量机: csdiy/datawhale_m4ai/12.md
  - CTF: 
    - 笔记目录: ctf/index.md
    - CTF101笔记: ctf/ctf101.md
    - Web笔记:
      - 导航: ctf/web/index.md
      - 西电CTF平台: ctf/web/xidianmoe.md
    - crypto笔记: 
      - 导航: ctf/crypto/index.md
      - CTF101课程遗留问题探索: ctf/crypto/ctf101.md
      - cryptohack基础: ctf/crypto/cryptohack_basic.md
      - RSA: ctf/crypto/rsa.md
      - DSA: ctf/crypto/dsa.md
      - AES: ctf/crypto/aes.md
      - Lattice: ctf/crypto/lattice.md
      - PRNG: ctf/crypto/prng.md
      - Hash Function: ctf/crypto/hash.md
      - ZJUSEC题库: ctf/crypto/zjusec.md
      - NSSCTF题库: ctf/crypto/nssctf.md
      - CSACTF2025: ctf/crypto/csactf2025.md
      - 长城杯2025: ctf/crypto/ccb2025.md
    - NewStarCTF2025:
      - 题解: ctf/newstarctf2025/writeup.md
  - 科研学习:
    - 收集帖: lab/index.md
    - Infiniflow: lab/infiniflow.md
  - OJ笔记:
    - OJ笔记导航: oj/index.md
    - LeetCode: 
      - 导航: oj/leetcode/index.md
      - 数组: oj/leetcode/int.md
      - 链表: oj/leetcode/linklist.md
      - 回溯: oj/leetcode/backtrack.md
      - 动态规划: oj/leetcode/dp.md
      - 贪心: oj/leetcode/greedy.md
    - USTC Verilog OJ: 
      - 导航: oj/ustcverilog/index.md
      - 题解: oj/ustcverilog/writeup.md
    - 图灵完备(Turing Complete): 
      - 导航: oj/turingcomplete/index.md
      - 题解: oj/turingcomplete/writeup.md
  - 编程语言&工具备忘:
    - 工具目录: tools/index.md
    - Markdown: tools/markdown.md
    - Linux: tools/linux.md
    - Python: tools/python.md
    - C++: tools/cpp.md
    - Windows Command Line: tools/bash.md
    - Windows小tips: tools/windows.md
    - JavaScript语言: tools/JavaScript.md
  - 储物柜:
    - Grapesea的小创作: 
      - 目录: gadgets/article/index.md
      - 2025个人向新年献词: gadgets/article/2025ny.md
      - 2026个人向新年展望: gadgets/article/2026ny.md
    - 摄影从0开始:
      - 资源目录: gadgets/photography/index.md
    - 旅途记录:
      - 上海一日游: gadgets/travel/tour_sh_1.md
  - 友链:
    - Grapesea的朋友们: friends/friends.md
    - Grapesea的其他联系方式: friends/contact.md
    