site_name: Grapesea's Notebook
repo_url: https://github.com/Grapesea/Notebook
repo_name: Notebook
use_directory_urls: false
theme: 
  name: material
  font:
    text: "Times New Roman"
    code: "Roboto Mono"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  language: zh
  logo: graph/logo.png
# pages:
# - [index.md, Home]
# - [about.md, About]
  favicon: graph/logo.png
  features:
    - search.highlight
#    - navigation.instant
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - git-revision-date-localized
    - git-creation-date
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      fallback_to_build_date: true
      enable_git_follow: false

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      linenums: true
      pygments_lang_class: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - footnotes
  - attr_list

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/image-lightbox.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - 首页: index.md
  - ZJU课程笔记: 
    - 导航栏: zju/index.md
    - 资源整合: zju/mix_resource.md
    - ZJU妙妙工具: zju/tools.md
    - 大一教训总结: zju/exp1.md
    - 大一笔记拾遗: 
      - 导航: zju/12/index.md
      - 线性代数知识拾遗:
        - 大纲: zju/12/la/index.md
      - 数据结构基础: 
        - 概述: zju/12/fds/index.md
        - Tree: zju/12/fds/tree.md
        - Heap: zju/12/fds/heap.md
        - Graph: zju/12/fds/graph.md
        - Testing: zju/12/fds/testing.md
    - 大二秋冬笔记: 
      - 导航: zju/21/index.md
      - 高级数据结构与算法分析: 
        - 概述: zju/21/ads/index.md
        - 高级数据结构:
          - AVL Tree & Splay Tree & Red-Black Tree & B+ Tree(√): zju/21/ads/tree.md
          - Amortized Analysis(√): zju/21/ads/amortized.md
          - Inverted File Index(√): zju/21/ads/fileindex.md
          - Leftist Heap & Skew Heap & Binomial Queue(√): zju/21/ads/heap.md
        - 算法分析:
          - Backtracking(√): zju/21/ads/bt.md
          - Divide and Conquer(√): zju/21/ads/dc.md
          - Dynamic Programming(√): zju/21/ads/dp.md
          - Greedy Algorithm(√): zju/21/ads/greedy.md
          - P&NP Completeness(√): zju/21/ads/np.md
          - Approximation Algorithm(√): zju/21/ads/approx.md
          - Local Search(√): zju/21/ads/local.md
          - Randomized Algorithm(√): zju/21/ads/random.md
          - Parallel Algorithm(√) : zju/21/ads/parallel.md
          - External Sort(√): zju/21/ads/exsort.md
        - Project:
          - Project 1-Comparing Different Search Trees: zju/21/ads/proj/1.md
          - Project 2-Shortest Path Algorithm with Heaps: zju/21/ads/proj/2.md
          - Project 3-Recover the Design: zju/21/ads/proj/3.md
          - Project 5-Three Partition: zju/21/ads/proj/5.md
      - 计算机组成: 
        - 概述: zju/21/co/index.md
        - 笔记:
          - 导航: zju/21/co/note/index.md
          - Chap1笔记: zju/21/co/note/co1.md
          - Chap2笔记: zju/21/co/note/co2.md
          - Chap3笔记: zju/21/co/note/co3.md
          - Chap4笔记: zju/21/co/note/co4.md
          - Chap5笔记: zju/21/co/note/co5.md
          - Chap6笔记: zju/21/co/note/co6.md
        - lab总结:
          - 导航: zju/21/co/lab/index.md
          - lab0:Vivado_Starter: zju/21/co/lab/lab0.md
          - lab1:Warmup: zju/21/co/lab/lab1.md
          - lab2:SCPU: zju/21/co/lab/lab2.md
          - lab3:Multiplier/Divider/Floating-Point Adder: zju/21/co/lab/lab3.md
          - lab4:CPU(Single Cycle): zju/21/co/lab/lab4.md
          - lab5:PipelineCPU: zju/21/co/lab/lab5.md
      - 面向对象程序设计: 
        - 概述: zju/21/oop/index.md
        - 笔记: 
          - Week1: zju/21/oop/1.md
          - Week2: zju/21/oop/2.md
          - Week3: zju/21/oop/3.md
          - Week4: zju/21/oop/4.md
          - Week5: zju/21/oop/5.md
          - Week6: zju/21/oop/6.md
          - 考前抱佛脚: zju/21/oop/review.md
        - 课程作业题干: 
          - Lab 1: zju/21/oop/lab/1.md
          - Lab 2: zju/21/oop/lab/2.md
          - Lab 3: zju/21/oop/lab/3.md
          - Lab 4: zju/21/oop/lab/4.md
          - Lab 5: zju/21/oop/lab/5.md
          - Lab 6: zju/21/oop/lab/6.md
          - Project 7: zju/21/oop/lab/7.md
      - 概率论与数理统计: 
        - 概述: zju/21/prob/index.md
        - 概率论: zju/21/prob/prob.md
        - 数理统计: zju/21/prob/statistic.md
      - 普通物理学II(H): 
        - 概述: zju/21/phy/index.md
      - 普通物理学实验II:
        - 概述: zju/21/phylab/index.md
      - 马克思主义基本原理(H):
        - 概述: zju/21/marx/index.md
      - 生命教育概论:
        - 概述: zju/21/life/index.md
        - 笔记: zju/21/life/life.md
      - 经济法理论与实务:
        - 概述: zju/21/eco/index.md
      - 万物运转的奥秘（已退课）:
        - 概述: zju/21/physec/index.md
    - 大二春夏笔记: 
      - 导航: zju/22/index.md
      - 数据库系统: 
        - 概述: zju/22/db/index.md
      - 计算机体系结构:
        - 概述: zju/22/arch/index.md
      - 机器学习在数据分析上的实际运用（国际化课程）:
        - 概述: zju/22/ml/index.md
      - 离散数学: 
        - 概述: zju/22/dm/index.md
      - 中国现当代文学史I:
        - 概述: zju/22/lit/index.md
        - 阅读材料: zju/22/lit/reading.md
        - 阅读材料笔记-1: zju/22/lit/notes0.md
        - 阅读材料笔记-2: zju/22/lit/notes1.md
        - 课程笔记-1: zju/22/lit/notes2.md
        - 课程笔记-2: zju/22/lit/notes3.md 
      - 工程图学(H):
        - 概述: zju/22/graphics/index.md
      - 生命科学导论(H):
        - 概述: zju/22/bio/index.md
      - 中国书画鉴赏:
        - 概述: zju/22/art/index.md
      - 毛概:
        - 概述: zju/22/mao/index.md
      - 创新创业实践启蒙:
        - 概述: zju/22/busi/index.md
      - 大学生朋辈心理辅导:
        - 概述: zju/22/psy/index.md
    - 大三秋冬笔记: 
      - 导航: zju/31/index.md
      - HPC101: csdiy/hpc101/index.md
      - 金融科技概论(课程综合实践II): 
        - 概述: zju/31/summer2/index.md
      - 计算理论: 
        - 概述: zju/31/toc/index.md
      - 操作系统: 
        - 概述: zju/31/os/index.md
      - 计算机网络:         
        - 概述: zju/31/web/index.md
      - B/S体系软件设计: 
        - 概述: zju/31/bs/index.md
      - 自然语言处理: 
        - 概述: zju/31/nlp/index.md
      - 习概: 
        - 概述: zju/31/xjp/index.md
  - 语言学习:
    - 导航栏: language/index.md
    - IELTS:
      - 资源整合: language/IELTS/index.md
      - 口语: language/IELTS/speaking.md
      - 听力: language/IELTS/listening.md
      - 阅读: language/IELTS/reading.md
      - 作文: language/IELTS/writing.md
    - CET6:
      - 资源整合: language/CET6/index.md
      - 单词: language/CET6/words.md
      - 作文: language/CET6/writing.md
  - CSDIY: 
    - CSDIY笔记导航: csdiy/index.md
    - Basics (Algorithm & Discrete Math & Programming):
      - Datawhale Mathematics for Artificial Intelligence:
        - 课程计划: csdiy/datawhale_m4ai/index.md
        - Chap 2-6:线性代数/解析几何/矩阵分解/向量微积分/概率与统计: csdiy/datawhale_m4ai/2-6.md
        - Chap 7:连续优化: csdiy/datawhale_m4ai/7.md
        - Chap 8:当模型遇上数据: csdiy/datawhale_m4ai/8.md
        - Chap 9:线性回归: csdiy/datawhale_m4ai/9.md
        - Chap 10:降维与主成分分析: csdiy/datawhale_m4ai/10.md
        - Chap 11:密度估计和Gauss混合模型: csdiy/datawhale_m4ai/11.md
        - Chap 12:分类和支持向量机: csdiy/datawhale_m4ai/12.md
      - CS70: 
        - 课程计划: csdiy/cs70/index.md
        - Proof & Stable matching: csdiy/cs70/1.md
        - Graph & Number theory & RSA: csdiy/cs70/2.md
        - Counting & Probability: csdiy/cs70/3.md
      - NJU-SICP:
        - 课程计划: csdiy/sicp-NJU/index.md
        - lec1-6: csdiy/sicp-NJU/lec1-6.md
        - lec7-12: csdiy/sicp-NJU/lec7-12.md
        - lec13-18: csdiy/sicp-NJU/lec13-18.md
      - CS61B:
        - 课程计划: csdiy/cs61b/index.md
        - Introduction: csdiy/cs61b/intro.md
        - Tree: csdiy/cs61b/tree.md
        - Heap: csdiy/cs61b/heap.md
        - Graph: csdiy/cs61b/graph.md
      - CS106L:
        - 课程计划: csdiy/cs106l/index.md
        - Lec1-Brief Introduction: csdiy/cs106l/1intro.md
        - Lec2-Types and Struct: csdiy/cs106l/2types.md
        - Lec3&4-Streams, Initialization and References: csdiy/cs106l/3_4streams_init_ref.md
        - Lec5&6-Containers,Iterators and Pointers: csdiy/cs106l/5_6container_iterator.md
        - Lec7~9-Classes, Template Classes, Template Functions: csdiy/cs106l/7_8_9classes_templates_func.md
        - Lec10~12-Functions, Lambda Functions, Operators and Special Member Functions: csdiy/cs106l/10_11_12function_operator_special.md
        - Lec13~15-Move Semantics, std::optional, type safety, RAII, smart poiters: csdiy/cs106l/13_14_15move_semantics_optional_smart_pointer_raii.md
    - CS61C (UCB):
      - 课程计划: csdiy/cs61c/index.md
    - NJU-ICSPA:
      - 课程计划: csdiy/icspa-NJU/index.md
    - HPC 101 (ZJU 2026):
      - 课程计划: csdiy/hpc101/index.md
      - 课程笔记:
        - 集群软硬件及运维基础(7.6): csdiy/hpc101/notes/cluster.md
        - 计算机系统基础(7.7-7.8): csdiy/hpc101/notes/system.md
        - 华为Ascend C异构框架基础(Extra): csdiy/hpc101/notes/ascendC.md
        - 向量化计算(7.10): csdiy/hpc101/notes/vector.md
        - OpenMP并行计算基础(7.12): csdiy/hpc101/notes/openmp.md
        - Performance Profiling(7.12): csdiy/hpc101/notes/perfprofile.md
        - GPU基础(7.13): csdiy/hpc101/notes/gpu-arch.md
        - GPU Programming(7.13): csdiy/hpc101/notes/gpu-program.md
        - 分布式训练(7.16): csdiy/hpc101/notes/dist_train.md
        - 机器学习基础(7.16): csdiy/hpc101/notes/ml-basics.md
        - HPC讲座(7.17): csdiy/hpc101/notes/hpc_lec.md
      - Labs:
        - Lab 00 (Setup): csdiy/hpc101/lab0.md
        - Lab 01 (简单集群搭建): csdiy/hpc101/lab1.md
        - Lab 02 (MoE的向量化计算): csdiy/hpc101/lab2.md
        - Lab 03 (GDN Prefill 前向优化): csdiy/hpc101/lab3.md
        - Lab 3.5 (昇腾算子优化): csdiy/hpc101/lab3p5.md
        - Lab 04 (AMSS-NCKU 数值相对论程序优化): csdiy/hpc101/lab4.md
        - Lab 4.5 (基于 INT8 张量核的 FP64 GEMM 模拟): csdiy/hpc101/lab4p5.md
        - Lab 05 (Gemma4 端到端推理优化): csdiy/hpc101/lab5.md
        - Project (鲲鹏高性能计算全球挑战赛-S2赛季): csdiy/hpc101/project.md
      - Ascend C 学习笔记: csdiy/hpc101/CANN.md
      - Debian 配置记录: csdiy/hpc101/Debian_settings.md
    - CSAPP (CMU):
      - 课程计划: csdiy/csapp/index.md
    - CMU 15-445:
      - 课程计划: csdiy/cmu15-445/index.md
      - Lec1-6 (SQL, Storage): csdiy/cmu15-445/1-6.md
      - Lec7-10 (Index): csdiy/cmu15-445/7-10.md
      - Lec11-16 (Algorithms, Query): csdiy/cmu15-445/11-16.md
      - Lec17-20 (Transaction, Lock): csdiy/cmu15-445/17-20.md
      - Lec21-25 (Misc): csdiy/cmu15-445/21-25.md
    - MIT 6.1810 Operating System (2025 Fall): 
      - 课程计划: csdiy/mit6.1810/index.md
      - 实验记录:
        - Lab00: csdiy/mit6.1810/labs/00.md
        - Lab01: csdiy/mit6.1810/labs/01.md
      - xv6文档阅读:
        - Chap 01: csdiy/mit6.1810/xv6/01.md
    - Stanford CS144 & UCB CS168 Computer Network:
      - 课程计划: csdiy/cs144/index.md
      - Introduction: csdiy/cs144/1.md
      - Checkpoint 0: csdiy/cs144/lab0.md
      - Checkpoint 1: csdiy/cs144/lab1.md
      - CS168课程计划: csdiy/cs168/index.md
      - CS168 Notes:
        - Lec1: csdiy/cs168/1.md
        - Lec2: csdiy/cs168/2.md
      - CS168 Projects:
        - Project 1: csdiy/cs168/labs/proj01.md

    - CS571:React(UW-Madison):
      - 课程计划: intern_work/web_develop/cs571/index.md
    - CS188 (UCB): 
      - 课程计划: csdiy/cs188/index.md
      - intro & search: csdiy/cs188/1.md
      - A* search & Heuristics: csdiy/cs188/2.md
      - CSPs: csdiy/cs188/3.md
      - Game Trees: csdiy/cs188/4.md
      - MDPs: csdiy/cs188/5.md
      - Appendix:Logic: csdiy/cs188/appendix.md
    - 李宏毅-通用AI模型時代下的機器學習:
      - 课程计划: csdiy/ml-lhy/index.md
    - CS224N:
      - 课程计划: lab/cs224n/index.md
    - CS224W:
      - 课程计划: lab/cs224w/index.md
    - Datawhale Hello-agent:
      - 课程计划: csdiy/datawhale_hello_agent/index.md
    - 斋藤康毅-深度学习(鱼书):
      - 书籍信息: csdiy/fish-dl/index.md
      - Chap 2: csdiy/fish-dl/Chap2-Perceptron.md
      - Chap 3: csdiy/fish-dl/Chap3-NeuralNetwork.md
      - Chap 4: csdiy/fish-dl/Chap4-Learning.md
      - Chap 5: csdiy/fish-dl/Chap5-BackPropagation.md
    - 李沐-动手学深度学习:
      - 课程计划: csdiy/d2l/index.md
      - Note 1:深度学习简介与工具准备: csdiy/d2l/intro.md
      - Note 2:数学基础: csdiy/d2l/mathbasics.md
    - 赵世钰-强化学习的数学原理:
      - 课程计划: csdiy/math_founda_rein_learn/index.md
    - Blockchain技术:
      - 资源整合: ctf/blockchain/index.md
      - UBC暑校: ctf/blockchain/ubc/index.md
    - Misc:
      - Datawhale Mathematical Modeling:
        - 课程计划: csdiy/datawhale_mm/index.md
        - Chap 1:解析方法与几何模型: csdiy/datawhale_mm/1.md  
        - Chap 2:微分方程与动力系统: csdiy/datawhale_mm/2.md
        - Chap 3:函数极值与规划模型: csdiy/datawhale_mm/3.md
        - Chap 4:复杂网络与图论模型: csdiy/datawhale_mm/4.md
        - Chap 5:进化计算与群体智能: csdiy/datawhale_mm/5.md
        - Chap 6:数据处理与拟合模型: csdiy/datawhale_mm/6.md
        - Chap 7:权重生成与评价模型: csdiy/datawhale_mm/7.md
        - Chap 8:时间序列与投资模型: csdiy/datawhale_mm/8.md
        - Chap 9:机器学习与统计模型: csdiy/datawhale_mm/9.md
        - Chap 10:图像、文本与信号数据: csdiy/datawhale_mm/10.md
  - 科研学习:
    - 收集帖: lab/index.md
    - RAGFlow: lab/ragflow.md
    - Datawhale All-in-RAG:
      - 课程计划: lab/datawhale-rag/index.md
      - Chap 1-3: lab/datawhale-rag/1-3.md
    - CS224N:
      - 课程计划: lab/cs224n/index.md
      - 笔记:
        - Lec1: lab/cs224n/notes/1.md
        - Lec2: lab/cs224n/notes/2.md
        - Lec3: lab/cs224n/notes/3.md
        - Lec5: lab/cs224n/notes/5.md
      - 论文阅读:
        - bert: lab/cs224n/papers/bert.md
        - Transformer: lab/cs224n/papers/attention_is_all_you_need.md
    - CS224W:
      - 课程计划: lab/cs224w/index.md
      - Lec01-02 (Introduction & Node Embedding): lab/cs224w/01-02.md
      - Lec03-05 (GNN): lab/cs224w/03-05.md
      - Lec06-08 (GNN Theory and Graph Transformer 1): lab/cs224w/06-08.md
      - 论文阅读:
        - node2vec: lab/cs224w/papers/node2vec.md
      - lab: 
        - colab0: lab/cs224w/labs/colab0.md
        - colab1: lab/cs224w/labs/colab1.md
        - colab2: lab/cs224w/labs/colab2.md
    - 工具:
      - AutoFigure: lab/tools/autofigure.md
      - EasySpider: lab/tools/easyspider.md
    - Skills:
      - 论文阅读-维度分析: lab/skills/dim_db.md
      - 论文阅读-内容分析: lab/skills/read_inst.md
  - 实习&工作: 
    - 导航: intern_work/index.md
    - 笔试机试: 
      - 华为机试: 
        - 目录: intern_work/test/huawei/index.md
        - AI岗: 
          - 20260613选择: intern_work/test/huawei/AI_develop_choice/20260513.md
    - 实习资源整理:
      - 面经: intern_work/interview/index.md
      - 模拟面试1: intern_work/interview/virtual-1.md
      - 模拟面试2: intern_work/interview/virtual-2.md
    - 前端:
      - Vue框架: intern_work/frontend/vue-basics.md
    - Web开发:
      - CS571 (React / React Native): 
        - 课程资源: intern_work/web_develop/cs571/index.md
    - OJ笔记:
      - OJ笔记导航: intern_work/oj/index.md
      - LeetCode: 
        - 导航: intern_work/oj/leetcode/cpp/index.md
        - C++:
          - 数组: intern_work/oj/leetcode/cpp/int.md
          - 链表: intern_work/oj/leetcode/cpp/linklist.md
          - 树: intern_work/oj/leetcode/cpp/tree.md
          - 图论: intern_work/oj/leetcode/cpp/graph.md
          - 回溯: intern_work/oj/leetcode/cpp/backtrack.md
          - 动态规划: intern_work/oj/leetcode/cpp/dp.md
          - 贪心: intern_work/oj/leetcode/cpp/greedy.md
          - 探险模式: 
            - 数学: intern_work/oj/leetcode/cpp/random/math.md
          - Hot100: intern_work/oj/leetcode/cpp/hot100.md
        - MySQL:
          - 整理: intern_work/oj/leetcode/sql/note.md
          - 探险模式: intern_work/oj/leetcode/sql/random/note.md
      - 牛客网:
        - SQL: intern_work/oj/nowcode/sql/index.md
      - USTC Verilog OJ: 
        - 导航: intern_work/oj/ustcverilog/index.md
        - 题解: intern_work/oj/ustcverilog/writeup.md
      - 图灵完备(Turing Complete): 
        - 导航: intern_work/oj/turingcomplete/index.md
        - 题解: intern_work/oj/turingcomplete/writeup.md
  - 编程语言&工具备忘:
    - 工具目录: tools/index.md
    - Git拾遗: tools/git.md
    - Markdown: tools/markdown.md
    - Linux拾遗: tools/linux.md
    - Python: tools/python.md
    - C++: tools/cpp.md
    - Marp插件配置: tools/marp.md
    - Claude-Projects Prompts: tools/claude-projects.md
    - 网络配置拾遗: tools/ssh-web-vpn.md
  - CTF: 
    - 笔记目录: ctf/index.md
    - CTF101笔记: ctf/ctf101.md
    - Web笔记:
      - 导航: ctf/web/index.md
      - SQL注入: ctf/web/sql.md
      - 西电CTF平台: ctf/web/xidianmoe.md
    - Crypto笔记: 
      - 导航: ctf/crypto/index.md
      - CTF101课程遗留问题探索: ctf/crypto/ctf101.md
      - cryptohack基础: ctf/crypto/cryptohack_basic.md
      - RSA: ctf/crypto/rsa.md
      - DSA: ctf/crypto/dsa.md
      - AES: ctf/crypto/aes.md
      - Lattice: ctf/crypto/lattice.md
      - PRNG: ctf/crypto/prng.md
      - Hash Function: ctf/crypto/hash.md
      - ZJUSEC题库: ctf/crypto/zjusec.md
      - NSSCTF题库: ctf/crypto/nssctf.md
      - CSACTF2025: ctf/crypto/csactf2025.md
      - 长城杯2025: ctf/crypto/ccb2025.md
    - Blockchain笔记:
      - 资源页: ctf/blockchain/index.md
      - UBC暑校:
        - 资源页: ctf/blockchain/ubc/index.md
        - Day1 (Introduction): ctf/blockchain/ubc/1.md
        - Day2 (Bitcoin): ctf/blockchain/ubc/2.md
        - Day3 (Ethereum & Smart Contract): ctf/blockchain/ubc/3.md
        - Day4 (SSI & Solana): ctf/blockchain/ubc/4.md
        - Day5 (XRP & BSafe and BGIN): ctf/blockchain/ubc/5.md
        - Day6 (Blockchain & Quantum): ctf/blockchain/ubc/6.md
        - Day7 (Blockchain & AI): ctf/blockchain/ubc/7.md
    - NewStarCTF2025:
      - 题解: ctf/newstarctf2025/writeup.md
  - 储物柜:
    - Grapesea的小创作: 
      - 目录: gadgets/article/index.md
      - 2025个人向新年献词: gadgets/article/2025ny.md
      - 2026个人向新年展望: gadgets/article/2026ny.md
    - 摄影从0开始:
      - 资源目录: gadgets/photography/index.md
    - 旅途记录:
      - 上海1日游: gadgets/travel/shanghai_1.md
      - 苏州1.5日游: gadgets/travel/suzhou_1.md
      - 无锡1.5日游: gadgets/travel/wuxi_1.md
      - 临安太子尖(20260426): gadgets/travel/taizijian20260426.md
      - 丽水3日游: gadgets/travel/lishui_1.md
      - 温哥华2周旅行见闻: gadgets/travel/vancouver.md
  - 友链:
    - Grapesea的朋友们: friends/friends.md
    - Grapesea的其他联系方式: friends/contact.md
