site_name: Grapesea's Notebook
repo_url: https://github.com/Grapesea/Notebook
repo_name: Notes
theme: 
  name: material
  font:
    text: "Times New Roman"
    code: "Roboto Mono"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  language: zh
  logo: graph/logo.png
# pages:
# - [index.md, Home]
# - [about.md, About]
  favicon: graph/logo.png
  features:
    - search.highlight
#    - navigation.instant
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - attr_list

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页: index.md
  - ZJU课程笔记: 
    - 导航栏: zju/index.md
    - 资源整合: zju/mix_resource.md
    - 培养计划: zju/course_info_blank.md
    - 大一教训总结: zju/exp1.md
    - 大二秋冬笔记: 
      - 导航: zju/21/index.md
      - 高级数据结构与算法分析: 
        - 概述: zju/21/ads/index.md
        - 数据结构: zju/21/ads/ds.md
        - 算法分析: zju/21/ads/algorithm.md
      - 计算机组成: 
        - 概述: zju/21/co/index.md
        - 计算机组成: zju/21/co/co.md
      - 面向对象程序设计: zju/21/oop.md
      - 概率论与数理统计: zju/21/prob.md
      - 普通物理学II(H): zju/21/phy.md
    - 大二春夏笔记: 
      - 导航: zju/22/index.md
      - 离散数学: zju/22/dm.md
  - csdiy课程笔记: 
    - csdiy课程笔记导航: csdiy/index.md
    - CS70: 
      - 课程计划: csdiy/1.cs70/index.md
      - proof & stable matching: csdiy/1.cs70/1.md
      - graph & number theory & RSA: csdiy/1.cs70/2.md
      - counting & probability: csdiy/1.cs70/3.md
    - CS188: 
      - 课程计划: csdiy/2.cs188/index.md
      - intro & search: csdiy/2.cs188/1.md
      - A* search & Heuristics: csdiy/2.cs188/2.md
      - CSPs: csdiy/2.cs188/3.md
      - Game Trees: csdiy/2.cs188/4.md
      - MDPs: csdiy/2.cs188/5.md
      - Appendix:Logic: csdiy/2.cs188/appendix.md
  - CTF: 
    - 笔记目录: ctf/index.md
    - CTF101笔记: ctf/ctf101.md
    - crypto笔记: 
      - 导航: ctf/crypto/index.md
      - 校巴wp: ctf/crypto/zjusec.md
      - cryptohack笔记: ctf/crypto/cryptohack.md
      - CSACTF2025: ctf/crypto/csactf2025.md
      - nssctf: ctf/crypto/nssctf.md
    - misc笔记: 
      - 导航: ctf/misc/index.md
    - web笔记: 
      - 导航: ctf/web/index.md
    - reverse笔记: 
      - 导航: ctf/reverse/index.md
    - pwn笔记: 
      - 导航: ctf/pwn/index.md
  - 工具备忘:
    - 工具目录: tools/index.md
    - Markdown: tools/markdown.md
    - Linux: tools/linux.md
    - Python: tools/python.md