site_name: Grapesea's Notebook
repo_url: https://github.com/Grapesea/Notebook
repo_name: Notebook
theme: 
  name: material
  font:
    text: "Times New Roman"
    code: "Roboto Mono"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  language: zh
  logo: graph/logo.png
# pages:
# - [index.md, Home]
# - [about.md, About]
  favicon: graph/logo.png
  features:
    - search.highlight
#    - navigation.instant
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - attr_list

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页: index.md
  - ZJU课程笔记: 
    - 导航栏: zju/index.md
    - 资源整合: zju/mix_resource.md
    - 培养计划: zju/course_info_blank.md
    - 大一教训总结: zju/exp1.md
    - 大二秋冬笔记: 
      - 导航: zju/21/index.md
      - 高级数据结构与算法分析: 
        - 概述: zju/21/ads/index.md
        - 数据结构: zju/21/ads/ds.md
        - 算法分析: zju/21/ads/algorithm.md
      - 计算机组成: 
        - 概述: zju/21/co/index.md
        - 计算机组成: zju/21/co/co.md
      - 面向对象程序设计: 
        - 概述: zju/21/oop/index.md
        - 笔记: zju/21/oop/oop.md
      - 概率论与数理统计: 
        - 概述: zju/21/prob/index.md
        - 概率论: zju/21/prob/prob.md
        - 数理统计: zju/21/prob/statistic.md
      - 普通物理学II(H): 
        - 概述: zju/21/phy/index.md
        - 电学: zju/21/phy/electricity/index.md  
        - 磁学: zju/21/phy/magnetism/index.md
        - 光学: zju/21/phy/optics/index.md
        - 量子力学: zju/21/phy/quantum/index.md
      - 马克思主义基本原理(H):
        - 概述: zju/21/marx/index.md
        - 笔记: zju/21/marx/marx.md
    - 大二春夏笔记: 
      - 导航: zju/22/index.md
      - 离散数学: 
        - 概述: zju/22/dm/index.md
        - 笔记: zju/22/dm/dm.md
  - csdiy课程笔记: 
    - csdiy课程笔记导航: csdiy/index.md
    - CS70: 
      - 课程计划: csdiy/cs70/index.md
      - Proof & Stable matching: csdiy/cs70/1.md
      - Graph & Number theory & RSA: csdiy/cs70/2.md
      - Counting & Probability: csdiy/cs70/3.md
    - CS188: 
      - 课程计划: csdiy/cs188/index.md
      - intro & search: csdiy/cs188/1.md
      - A* search & Heuristics: csdiy/cs188/2.md
      - CSPs: csdiy/cs188/3.md
      - Game Trees: csdiy/cs188/4.md
      - MDPs: csdiy/cs188/5.md
      - Appendix:Logic: csdiy/cs188/appendix.md
  - CTF: 
    - 笔记目录: ctf/index.md
    - CTF101笔记: ctf/ctf101.md
    - crypto笔记: 
      - 导航: ctf/crypto/index.md
      - RSA: ctf/crypto/rsa.md
      - DSA: ctf/crypto/dsa.md
      - Coppersmith: ctf/crypto/coppersmith.md
      - PRNG: ctf/crypto/prng.md
      - CTF101课程遗留问题探索: ctf/crypto/ctf101.md
      - 校巴wp: ctf/crypto/zjusec.md
      - cryptohack笔记: ctf/crypto/cryptohack.md
      - CSACTF2025: ctf/crypto/csactf2025.md
      - NSSCTF题库: ctf/crypto/nssctf.md
    - misc笔记: 
      - 导航: ctf/misc/index.md
    - web笔记: 
      - 导航: ctf/web/index.md
    - reverse笔记: 
      - 导航: ctf/reverse/index.md
    - pwn笔记: 
      - 导航: ctf/pwn/index.md
  - OJ笔记:
    - OJ笔记导航: oj/index.md
    - LeetCode: 
      - 导航: oj/leetcode/index.md
      - 数组: oj/leetcode/int.md
      - 链表: oj/leetcode/linklist.md
    - USTC VOJ: 
      - 导航: oj/ustcverilog/index.md
    - 洛谷: 
      - 导航: oj/luogu/index.md
  - 工具备忘:
    - 工具目录: tools/index.md
    - Markdown: tools/markdown.md
    - Linux: tools/linux.md
    - Python: tools/python.md